server:
  port: 80

eureka:
  instance:
    instance-id: orderHystrix80
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  zipkin:
    base-url: http://localhost:9441
  sleuth:
    sampler:
      probability: 1  # 采样率，介于0-1之间，1标识全部采集

# Ribbon超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


feign:
  hystrix:
    enabled: true