server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # sentinel 监控地址
        dashboard: localhost:8081
        # sentinel api端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
