server:
  port: 84

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8081
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"


service:
  provider:
    payment: http://cloudalibaba-sentinel-service

feign:
  sentinel:
    enabled: true