server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost:2183


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zh.springcloud.entities
